name: Backend CI

on:
  push:
    paths:
      - 'apps/backend/**'
  pull_request:
    paths:
      - 'apps/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r apps/backend/requirements.txt
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings --tb=short apps/backend/tests/
      - name: Upload coverage report
        run: |
          pip install coverage
          coverage run -m pytest apps/backend/tests/
          coverage xml
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
        continue-on-error: true
