name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      # 🆕 Auto-resize icons step (prevents icon size errors forever)
      - name: Ensure icon size is at least 256x256
        run: |
          mkdir -p apps/web/build
          # Install imagemagick depending on runner
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y imagemagick
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install imagemagick
          fi
          # Resize appicon2.png to 512x512 (only if smaller)
          if [ -f apps/web/build/appicon2.png ]; then
            convert apps/web/build/appicon2.png -resize 512x512\> apps/web/build/appicon2.png
          else
            echo "❌ appicon2.png not found!"
            exit 1
          fi

      - name: Build Electron App
        run: npm run build
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-${{ runner.os }}
          path: apps/web/dist/**

