name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      # Linux setup
      - name: Install ImageMagick on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick icoutils
          which magick || which convert

      # macOS setup
      - name: Install ImageMagick on macOS
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick icoutils || true
          which magick || which convert

      # Windows setup
      - name: Install ImageMagick on Windows
        if: runner.os == 'Windows'
        run: |
          choco install imagemagick -y --no-progress
          refreshenv
          where magick

      # Make sure icons folder exists (cross-platform safe)
      - name: Create icons directory
        run: mkdir -p apps/web/build/icons
        shell: bash

      # Generate icons (force use of `magick` or fallback `convert`)
      - name: Generate app icons
        run: |
          IMG_CMD=$(command -v magick || command -v convert)
          $IMG_CMD apps/web/build/appicon2.png -resize 512x512! apps/web/build/icons/appicon.png
          $IMG_CMD apps/web/build/icons/appicon.png -define icon:auto-resize=256,128,64,48,32,16 apps/web/build/icons/appicon.ico
        shell: bash

      - name: Build Electron App
        run: npm run build
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-${{ runner.os }}
          path: apps/web/dist/**
