name: Build & Release CraftedJewelz

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd apps/web
          npm install

      - name: Ensure build directories
        run: |
          mkdir -p apps/web/build/icons
          mkdir -p apps/web/assets

      - name: Copy provided 512x512 appicon2.png into icons
        run: |
          cp apps/web/build/appicon2.png apps/web/build/icons/icon.png
          cp apps/web/build/appicon2.png apps/web/build/icons/icon.icns
          cp apps/web/build/appicon2.png apps/web/build/icons/icon.ico
        shell: bash

      - name: Build Electron App
        run: |
          cd apps/web
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-build-${{ matrix.os }}
          path: apps/web/dist/*

