name: Build CraftedJewelz

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/web
          npm install --legacy-peer-deps

      - name: Build app
        run: |
          cd apps/web
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-build
          path: apps/web/dist/**
