name: Build & Publish Installers

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify GH_TOKEN exists
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ ERROR: GH_TOKEN secret is missing. Please add it in GitHub → Settings → Secrets → Actions."
            exit 1
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      - name: Build frontend
        run: npm run build
        working-directory: apps/web

      - name: Package Electron App
        run: |
          echo "Using GH_TOKEN: ${{ secrets.GH_TOKEN:0:4 }}****"
          npx electron-builder --publish always --x64
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
