name: Build & Publish Installers

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # --- Install dependencies for icon resizing ---
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick icnsutils graphicsmagick

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick graphicsmagick
          # icnsutils not available in brew, imagemagick handles .icns

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install imagemagick --yes --no-progress

      # --- Safe mkdir ---
      - name: Create icons directory (cross-platform safe)
        run: |
          if [ ! -d "apps/web/build/icons" ]; then
            mkdir -p apps/web/build/icons
          fi
        shell: bash

      # --- Resize appicon2.png into required sizes ---
      - name: Generate icons
        run: |
          magick apps/web/build/appicon2.png -resize 512x512 apps/web/build/icons/icon.png
          magick apps/web/build/appicon2.png -resize 512x512 apps/web/build/icons/icon.icns
          magick apps/web/build/appicon2.png -resize 512x512 apps/web/build/icons/icon.ico
        shell: bash

      # --- Install dependencies & build ---
      - name: Install npm deps
        working-directory: apps/web
        run: npm install

      - name: Build with electron-builder
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      # --- Upload artifacts ---
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CraftedJewelz-installers
          path: apps/web/dist/*
