name: Build & Publish Installers

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y icnsutils graphicsmagick imagemagick

      - name: Install dependencies (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          brew install imagemagick graphicsmagick icoutils

      - name: Ensure assets folder exists
        run: |
          mkdir -p apps/web/assets
          mkdir -p apps/web/build/icons
          echo "Ensured assets and icons folders exist."

      - name: Install npm dependencies
        working-directory: apps/web
        run: npm install

      - name: Build Electron App
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CraftedJewelz-${{ matrix.os }}
          path: apps/web/dist/**
