name: Build & Publish Installers

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      # Fix: don’t fail if icons folder already exists
      - name: Ensure build/icons folder exists
        shell: bash
        run: |
          if [ ! -d "apps/web/build/icons" ]; then
            mkdir -p apps/web/build/icons
          fi

      # Copy your 512x512 icon into the icons folder
      - name: Copy appicon2.png
        run: |
          cp apps/web/build/appicon2.png apps/web/build/icons/appicon.png

      - name: Build installers
        run: npm run build
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CraftedJewelz-${{ matrix.os }}
          path: apps/web/dist/**
