name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/web
        run: npm install

      - name: Build Electron App
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx electron-builder --publish always

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-${{ matrix.os }}
          path: apps/web/dist/*



