name: Build Installers

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      - name: Build Vite
        run: npm run build
        working-directory: apps/web

      - name: Build Installers
        run: npx electron-builder --publish always --x64
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
