name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/web
        run: npm install

      - name: Prepare icons
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y icnsutils imagemagick
          mkdir -p apps/web/build/icons
          cp apps/web/build/appicon2.png apps/web/build/icons/appicon.png
          # Create ICNS for macOS
          png2icns apps/web/build/icons/appicon.icns apps/web/build/appicon2.png
          # Create ICO for Windows
          convert apps/web/build/appicon2.png -resize 256x256 apps/web/build/icons/appicon.ico

      - name: Build and Publish
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always --x64



