name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      # Linux: install Imagemagick + icoutils
      - name: Install tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick icoutils

      # macOS: install Imagemagick
      - name: Install tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install imagemagick icoutils || true

      # Windows: install Imagemagick
      - name: Install tools (Windows)
        if: runner.os == 'Windows'
        run: choco install imagemagick -y

      # Generate icons cross-platform
      - name: Generate app icons
        run: |
          mkdir -p apps/web/build/icons
          magick convert apps/web/build/appicon2.png -resize 512x512! apps/web/build/icons/appicon.png
          magick convert apps/web/build/icons/appicon.png -define icon:auto-resize=256,128,64,48,32,16 apps/web/build/icons/appicon.ico

      - name: Build Electron App
        run: npm run build
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-${{ runner.os }}
          path: apps/web/dist/**
