name: Build & Publish Installers

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ensure icons directory exists
        run: |
          if [ ! -d "apps/web/build/icons" ]; then
            mkdir -p apps/web/build/icons
          fi
        shell: bash

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick graphicsmagick icnsutils

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install imagemagick graphicsmagick icoutils

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install imagemagick graphicsmagick -y

      - name: Install npm dependencies
        working-directory: apps/web
        run: npm install

      - name: Build installers
        working-directory: apps/web
        run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: craftedjewelz-installers
          path: apps/web/dist/**

