name: Build & Auto-Publish CraftedJewelz

on:
  push:
    branches:
      - main   # every push to main triggers
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: apps/web

      - name: Auto bump version
        id: version
        run: |
          VERSION=$(npm --prefix apps/web version patch --no-git-tag-version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Electron app
        run: npx electron-builder --publish always --x64
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: CraftedJewelz v${{ steps.version.outputs.version }}
          files: apps/web/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}



