name: Publish on Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # ✅ allow publishing to Releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/web
        run: npm install

      - name: Sync version with tag
        working-directory: apps/web
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "Setting package.json version to $VERSION"
          npm version --no-git-tag-version $VERSION

      - name: Build & Publish
        working-directory: apps/web
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ use built-in token
        run: npx electron-builder --config ../../electron-builder.yml --publish always

