name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v4.0.2)"
        required: true
        default: "v4.0.2"

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build on ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json
      - name: Install dependencies
        run: |
          cd apps/web
          npm install --legacy-peer-deps
      - name: Prepare icons
        run: |
          cd apps/web
          mkdir -p build/icons
          cp build/appicon2.png build/icons/ || true
          cp build/dmg-background.png build/icons/ || true
      - name: Build Electron App
        run: |
          cd apps/web
          npm run build
      - name: Package Electron app
        run: |
          cd apps/web
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: CraftedJewelz ${{ github.ref_name }}
          files: apps/web/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

