name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v4.0.2)"
        required: true
        default: "v4.0.2"

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Prepare icons
        run: |
          mkdir -p build/icons
          cp build/appicon2.png build/icons/ || true
          cp build/dmg-background.png build/icons/ || true

      - name: Build Electron App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: CraftedJewelz ${{ github.event.inputs.version }}
          files: apps/web/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

